# ======
# Project Details
# ======
name: 'dbt_airflow'
version: '1.0'
config-version: 2
profile: 'dbt_airflow'
require-dbt-version: [">=1.0.0", "<2.0.0"]

# ======
# File Path Configs
# ======
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  dbt_airflow:
    +materialized: table